### ISSUE TITLE
Default path to bash on *BSD systems

### ISSUE THREAD

**Issue by eserte** [jo-37/shell-run#1]
On *BSD systems (e.g. FreeBSD) bash ist not located in /bin/bash, but in /usr/local/bin/bash (if it's installed at all). It would be nice if the different path would be set by default on these systems.

**Comment by jo-37** [comment]
As a linux user I didn't have a focus on this. Of course you are right and I'll add a path search for the bash executable.

**Comment by jo-37** [comment]
Made some more changes than the path to bash due to other suggestions. The usage has changed now and I renamed the package. The issue w.r.t. *BSD should be fixed now, provided /usr/local/bin is in the PATH.

Closing this issue.
